'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ArrowRight,Heart,HeartPulse,Stethoscope,Brain,Sparkles,ShieldCheck,CalendarDays,Search,Star,Check,ChevronDown,Plus,Menu,X,Video,Clock,MapPin,Leaf} from 'lucide-react';
import {doctors} from '@/lib/doctors';
type Doctor=typeof doctors[number];
const photo=(id:string,w=600)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=85`;
export default function Home(){
 const [specialty,setSpecialty]=useState('All specialties');const [query,setQuery]=useState('');const [results,setResults]=useState(doctors);const [searchError,setSearchError]=useState('');const [selected,setSelected]=useState<Doctor|null>(null);const [menu,setMenu]=useState(false);const [faq,setFaq]=useState<number|null>(0);
 const [searching,setSearching]=useState(false);
 const [searchSummary,setSearchSummary]=useState('');
 const searchRequest=useRef<AbortController|null>(null);
 useEffect(()=>()=>searchRequest.current?.abort(),[]);
 function resetSearch(){searchRequest.current?.abort();setSearching(false);setSearchError('');setSearchSummary('');setResults(doctors);setSpecialty('All specialties');setQuery('')}
 async function search(e?:React.FormEvent,allSpecialties=false,suggestedQuery?:string){
  e?.preventDefault();searchRequest.current?.abort();
  const controller=new AbortController();searchRequest.current=controller;
  const term=(suggestedQuery??query).trim();if(suggestedQuery!==undefined)setQuery(suggestedQuery);const filter=allSpecialties?'All specialties':specialty;
  if(allSpecialties)setSpecialty('All specialties');
  setSearchError('');setSearching(true);setSearchSummary('Searching for your care…');
  try{
   const r=await fetch(`/api/doctors?q=${encodeURIComponent(term)}&specialty=${encodeURIComponent(filter)}`,{signal:controller.signal});
   if(!r.ok)throw Error();
   const data=await r.json();if(controller.signal.aborted)return;
   setResults(data.doctors);setSearchSummary(`${data.doctors.length} doctor${data.doctors.length===1?'':'s'} found${term?` for “${term}”`:''}${filter!=='All specialties'?` in ${filter}`:''}.`);
   document.getElementById('doctors')?.scrollIntoView({behavior:'smooth'});
  }catch{if(!controller.signal.aborted){setSearchError('Search is unavailable. Please try again.');setSearchSummary('')}}
  finally{if(!controller.signal.aborted)setSearching(false)}
 }

 const services=[{name:'Primary care',icon:Stethoscope,text:'Your everyday health, in expert hands.'},{name:'Cardiology',icon:HeartPulse,text:'Wholehearted care for a healthier you.'},{name:'Mental wellness',icon:Brain,text:'A safe space for your peace of mind.'},{name:'Dermatology',icon:Sparkles,text:'Feel confident in the skin you’re in.'}];
 return <><div className="announcement">A healthier tomorrow starts with a little care today. <a href="#services">Explore our care <ArrowUpRight size={13}/></a></div><header><a href="#" className="brand"><span className="brand-icon"><Plus strokeWidth={3}/></span>vitalis<span className="brand-health">health</span></a><nav className={menu?'mobile-open':''}><a href="#services" onClick={()=>setMenu(false)}>Our care</a><a href="#doctors" onClick={()=>setMenu(false)}>Find a doctor</a><a href="#approach" onClick={()=>setMenu(false)}>Why Vitalis</a><a href="#faq" onClick={()=>setMenu(false)}>Resources</a></nav><button className="button small nav-book" onClick={()=>setSelected(doctors[0])}>Book an appointment <ArrowUpRight size={16}/></button><button className="menu-button" aria-label="Toggle navigation" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
 <main><section className="site-search" aria-label="Search for healthcare">
  <div className="site-search-heading">
   <span className="search-heading-icon"><Sparkles size={20} strokeWidth={1.6}/></span>
   <div><span className="search-eyebrow">YOUR NEXT STEP TO FEELING BETTER</span><label htmlFor="site-search-input">Great care starts with a search.</label></div>
   <span className="search-top-note"><Heart size={13}/> Care, centered on you</span>
  </div>
  <form role="search" aria-label="Search doctors and specialties" onSubmit={e=>search(e,true)}>
   <div className="site-search-field">
    <Search className="search-input-icon" size={23} strokeWidth={1.7}/>
    <div className="search-input-wrap"><span className="search-field-caption" aria-hidden="true">DOCTOR, SPECIALTY, OR KEYWORD</span><input id="site-search-input" type="search" placeholder="Search doctors or specialties…" value={query} maxLength={100} onChange={e=>setQuery(e.target.value)}/></div>
    {query&&<button type="button" className="clear-search" aria-label="Clear search and show all doctors" onClick={resetSearch}><X size={17}/></button>}
   </div>
   <button type="submit" className="button search-submit" disabled={searching}><span>{searching?'Finding your care…':'Find my care'}</span><span className="search-submit-icon">{searching?<span className="search-spinner" aria-hidden="true"/>:<ArrowUpRight size={20}/>}</span></button>
  </form>
  <div className="search-discovery"><span className="search-popular-label">Try a specialty</span><div className="search-chips">{services.map(service=><button key={service.name} type="button" onClick={()=>search(undefined,true,service.name)} disabled={searching}><service.icon size={13} strokeWidth={1.7}/>{service.name}<ArrowUpRight className="chip-arrow" size={12}/></button>)}</div></div>
  <div className={`site-search-feedback${searchError?' search-has-error':''}`} aria-live="polite">{searchError||searchSummary||'A name you know. A specialist you need. We’ll help you find your fit.'}</div>
 </section><section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="dot"/> GOOD HEALTH. GREAT CARE.</div><h1>Healthcare that<br/>feels a little<br/><em>more human.</em></h1><p>Expert care. Real connection. A healthier you.<br/>Discover healthcare built around your life,<br className="desktop-break"/> not the other way around.</p><div className="hero-buttons"><button className="button" onClick={()=>setSelected(doctors[0])}>Find your care <ArrowUpRight size={18}/></button><a className="text-button" href="#approach">Meet Vitalis <span className="round-arrow"><ArrowRight size={16}/></span></a></div><div className="social-proof"><div className="avatars">{doctors.slice(0,3).map(d=><img key={d.id} src={photo(d.image,90)} alt=""/>)}</div><div><div className="stars">★★★★★ <strong>4.9<span>/5</span></strong></div><small>A little care makes a big difference</small></div></div></div><div className="hero-visual"><img className="hero-image" src={photo('photo-1576091160399-112ba8d25d1d',1200)} alt="Doctor listening thoughtfully to a patient during a consultation" fetchPriority="high"/><div className="image-tint"/><div className="visual-label"><span className="dot"/> HERE FOR YOU. ALWAYS.</div><div className="care-card"><span className="care-icon"><HeartPulse size={27}/></span><div><strong>Good care starts<br/>with listening.</strong><span>People first. Every single time.</span></div><span className="care-check"><Check size={13}/></span></div><div className="image-caption"><span>Care that sees the whole you.</span><ArrowUpRight size={25}/></div></div></section>
 <section className="finder" aria-label="Find care"><div className="finder-title"><Search size={23}/><div><h2>Your better health starts here.</h2><p>Let’s find the right care for you.</p></div></div><form onSubmit={e=>search(e)}><label><span>SPECIALTY</span><select value={specialty} onChange={e=>setSpecialty(e.target.value)}><option>All specialties</option>{services.map(s=><option key={s.name}>{s.name}</option>)}</select></label><label><span>DOCTOR OR KEYWORD</span><input placeholder="Who are you looking for?" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="button" type="submit" disabled={searching}>{searching?'Searching…':'Find a doctor'} <Search size={17}/></button></form>{searchError&&<p role="alert">{searchError}</p>}</section>
 <div className="trust-row"><span>Thoughtful care, every step of the way</span><div><ShieldCheck/> Vetted specialists</div><div><Video/> In-person & virtual</div><div><CalendarDays/> Easy online booking</div><div><Heart/> Personalized to you</div></div>
 <section className="section services" id="services"><div className="section-heading"><div><div className="eyebrow">CARE FOR EVERY CHAPTER</div><h2>A little support.<br/>A world of difference.</h2></div><p>From everyday checkups to specialized support,<br/>we’re here to help you feel your best.</p></div><div className="service-grid">{services.map((s,i)=><button className={`service-card service-${i}`} key={s.name} onClick={()=>{resetSearch();setSpecialty(s.name);setQuery('');setResults(doctors.filter(d=>d.specialty===s.name));document.getElementById('doctors')?.scrollIntoView({behavior:'smooth'})}}><div className="service-top"><span className="service-icon"><s.icon size={28} strokeWidth={1.5}/></span><ArrowUpRight size={20}/></div><h3>{s.name}</h3><p>{s.text}</p><span className="service-link">Explore care <ArrowRight size={14}/></span></button>)}</div></section>
 <section className="approach section" id="approach"><div className="approach-image"><img loading="lazy" src={photo('photo-1559757148-5c350d0d3c56',850)} alt="Healthcare professional providing attentive care"/><div className="approach-badge"><Leaf size={27}/><span>Better together.<br/><strong>Healthier for life.</strong></span></div></div><div className="approach-copy"><div className="eyebrow">A DIFFERENT KIND OF HEALTHCARE</div><h2>Not just a patient.<br/><em>A person. You.</em></h2><p>We believe feeling better starts with being heard. That’s why we bring together compassionate people, thoughtful technology, and care that goes the extra mile.</p><div className="benefit"><span><Check size={17}/></span><div><h3>More time for what matters</h3><p>Unhurried appointments. Real conversations.</p></div></div><div className="benefit"><span><Check size={17}/></span><div><h3>Your care, connected</h3><p>A team that works together, with you at the center.</p></div></div><div className="benefit"><span><Check size={17}/></span><div><h3>Here when you need us</h3><p>Flexible appointments that fit into your life.</p></div></div><a href="#doctors" className="text-button">Find your people <ArrowUpRight size={18}/></a></div></section>
 <section className="section doctors" id="doctors"><div className="section-heading"><div><div className="eyebrow">EXPERT HANDS. KIND HEARTS.</div><h2>Good people. Great doctors.</h2></div><button className="outline-button" onClick={resetSearch}>View all doctors <ArrowUpRight size={16}/></button></div><p className="section-subtitle">Meet a few of the people who put your wellbeing first.</p><p className="search-result-summary" role="status">{searchSummary}</p><div className="doctor-grid" aria-busy={searching}>{results.map(d=><article className="doctor-card" key={d.id}><div className="doctor-photo" style={{background:d.color}}><img src={photo(d.image)} alt={d.name} loading="lazy"/><span className="doctor-specialty">{d.specialty}</span><button className="doctor-arrow" aria-label={`Book ${d.name}`} onClick={()=>setSelected(d)}><ArrowUpRight size={21}/></button></div><div className="doctor-details"><h3>{d.name}</h3><p>{d.degree}</p><div className="doctor-meta"><span><Star size={13} fill="currentColor"/> {d.rating} <small>({d.reviews} reviews)</small></span><span>{d.experience} yrs exp.</span></div><button className="doctor-book" onClick={()=>setSelected(d)}><span><span className="dot"/> Check availability</span><ArrowRight size={15}/></button></div></article>)}</div>{results.length===0&&<div className="empty"><Search/><h3>No doctors found</h3><p>Try another name or specialty.</p><button className="button" onClick={resetSearch}>Show all doctors</button></div>}<p className="demo-note">Illustrative provider profiles and ratings. This is a demo, not a live medical service.</p></section>
 <section className="journey section"><div className="eyebrow">LESS FRICTION. MORE FEELING BETTER.</div><h2>Good care is just a few steps away.</h2><div className="steps">{[{title:'Find your perfect fit',text:'Explore our specialists and choose someone who feels right for you.',icon:Search},{title:'Make a little time for you',text:'Pick a time and an in-person or video visit that works for your day.',icon:CalendarDays},{title:'Let’s feel better, together',text:'Meet your doctor and take the next step toward a healthier you.',icon:Heart}].map((s,i)=><div key={s.title}><span className="step-number">0{i+1}</span><s.icon size={28} strokeWidth={1.4}/><h3>{s.title}</h3><p>{s.text}</p></div>)}</div></section>
 <section className="section faq" id="faq"><div><div className="eyebrow">A LITTLE CLARITY</div><h2>Questions?<br/>We’re here for you.</h2><p>Good care starts with good information.</p></div><div className="faq-list">{[{q:'How do I book an appointment?',a:'Choose a doctor, select an available date and time, and enter your contact details. Your booking is saved immediately and you receive a reference number on screen. This demo does not send email confirmations.'},{q:'Can I see a doctor from home?',a:'You can select “Video visit” in the appointment form. This demo records your preferred visit type. Video calls and real medical appointments are not provided.'},{q:'Do you accept my insurance?',a:'Insurance coverage varies by provider and plan. For a real appointment, always confirm coverage directly with your provider. This demo does not process insurance or payments.'},{q:'Is this for medical emergencies?',a:'No. If you are experiencing a medical emergency, call your local emergency number immediately. This website does not provide medical advice or emergency care.'}].map((item,i)=><div className="faq-item" key={item.q}><button aria-expanded={faq===i} onClick={()=>setFaq(faq===i?null:i)}>{item.q}{faq===i?<X size={17}/>:Plus&&<Plus size={17}/>}</button>{faq===i&&<p>{item.a}</p>}</div>)}</div></section>
 <section className="cta"><div className="cta-decoration"><HeartPulse size={180} strokeWidth={.6}/></div><div><div className="eyebrow">YOU DESERVE TO FEEL YOUR BEST.</div><h2>Your next chapter.<br/>A healthier you.</h2><p>Let’s take the first step, together.</p></div><button className="button light" onClick={()=>setSelected(doctors[0])}>Find your care <ArrowUpRight size={18}/></button></section></main>
 <footer><div className="footer-main"><div><a href="#" className="brand"><span className="brand-icon"><Plus strokeWidth={3}/></span>vitalis<span className="brand-health">health</span></a><p>A little more human.<br/>A whole lot more care.</p></div><div><h4>YOUR HEALTH</h4><a href="#services">Explore our care</a><a href="#doctors">Find a doctor</a><button onClick={()=>setSelected(doctors[0])}>Book an appointment</button></div><div><h4>GET TO KNOW US</h4><a href="#approach">Our approach</a><a href="#faq">Frequently asked questions</a><a href="#services">Our specialties</a></div><div className="footer-note"><Heart size={20}/><p>Made for people.<br/>Built around you.</p><span>For emergencies, call your local emergency number.</span></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Vitalis Health. Demo experience.</span><span>No medical advice. Do not enter sensitive health information.</span><span>Care comes full circle. <Leaf size={14}/></span></div></footer>{selected&&<Booking doctor={selected} close={()=>setSelected(null)}/>}</>;
}
function Booking({doctor,close}:{doctor:Doctor,close:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null);const [date,setDate]=useState(new Date(Date.now()+86400000).toISOString().slice(0,10));const [time,setTime]=useState('');const [available,setAvailable]=useState<string[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState('');
 useEffect(()=>{const el=dialog.current;el?.showModal();const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=overflow}},[]);
 useEffect(()=>{const ctrl=new AbortController();setLoading(true);setTime('');setError('');fetch(`/api/appointments?doctorId=${doctor.id}&date=${date}`,{signal:ctrl.signal}).then(async r=>{if(!r.ok)throw Error();setAvailable((await r.json()).slots)}).catch(e=>{if(e.name!=='AbortError'){setAvailable([]);setError('Unable to load availability. Please try another date.')}}).finally(()=>{if(!ctrl.signal.aborted)setLoading(false)});return()=>ctrl.abort()},[date,doctor.id]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!time)return;setSaving(true);setError('');const form=new FormData(e.currentTarget);try{const r=await fetch('/api/appointments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({doctorId:doctor.id,date,time,name:form.get('name'),email:form.get('email'),visitType:form.get('visitType')})});const data=await r.json();if(!r.ok){if(r.status===409){setAvailable(a=>a.filter(s=>s!==time));setTime('')}throw Error(data.error)}setSuccess(data.id)}catch(e){setError(e instanceof Error?e.message:'Unable to book. Please try again.')}finally{setSaving(false)}}
 return <dialog ref={dialog} className="booking-dialog" onCancel={close} aria-labelledby="booking-title"><button className="close-modal" aria-label="Close booking" onClick={close}><X size={21}/></button>{success?<div className="booking-success"><span className="success-icon"><Check size={35}/></span><div className="eyebrow">A LITTLE STEP FOR A HEALTHIER YOU</div><h2 id="booking-title">You’re all booked.</h2><p>Your demo appointment with <strong>{doctor.name}</strong> is saved.</p><div className="confirmation"><CalendarDays size={19}/>{date} at {time}<br/></div><p className="reference">Booking reference<br/><strong>{success}</strong></p><p className="demo-note">No email is sent and no real medical visit is scheduled.</p><button className="button" onClick={close}>Back to feeling good <ArrowRight size={17}/></button></div>:<><div className="eyebrow">MAKE TIME FOR YOURSELF</div><h2 id="booking-title">Your care starts here.</h2><div className="booking-doctor"><img src={photo(doctor.image,120)} alt=""/><div><h3>{doctor.name}</h3><p>{doctor.specialty} · ${doctor.fee} estimated visit</p></div><ShieldCheck size={23}/></div><form onSubmit={submit}><div className="form-row"><label>Date<input type="date" required value={date} min={new Date().toISOString().slice(0,10)} max={new Date(Date.now()+90*86400000).toISOString().slice(0,10)} onChange={e=>setDate(e.target.value)}/></label><label>Visit type<select name="visitType"><option>In-person</option><option>Video visit</option></select></label></div><fieldset><legend>Available times <span>(clinic local time)</span></legend><div className="time-slots">{loading?<p>Finding your time…</p>:available.length?available.map(t=><button type="button" key={t} aria-pressed={time===t} className={time===t?'active':''} onClick={()=>setTime(t)}>{t}</button>):<p>No times available. Please choose another date.</p>}</div></fieldset><label>Full name<input name="name" autoComplete="name" required minLength={2} maxLength={100} placeholder="Your full name"/></label><label>Email address<input name="email" type="email" autoComplete="email" required maxLength={254} placeholder="you@example.com"/></label><p className="demo-note">Demo only. Use fictional contact details. Do not include medical information. No payment required.</p>{error&&<p className="form-error" role="alert">{error}</p>}<button disabled={!time||saving||loading} className="button submit-booking">{saving?'Saving your appointment…':'Confirm appointment'} <ArrowRight size={17}/></button></form></>}</dialog>
}
